### ISSUE TITLE
test problem

### ISSUE THREAD

**Issue by Qilewuqiong** [uwsampa/grappa#237]
While I running:
bin/grappa_srun -n 2 -p 1 -- applications/demos/hello_world.exe
I get the error information:
bin/grappa_srun:80:in `exec': No such file or directory - srun (Errno::ENOENT)
        from bin/grappa_srun:80:in `<main>'
but when I run: bin/grappa_run -n 2 -p 1 -- applications/demos/hello_world.exe
I get the correct result
My ruby version is 2.2.0
Which ruby :~/lib/ruby/bin/ruby
$PATH: ~/lib/ruby/bin
How to fix the problem? Thank you.

**Comment by nelsonje** [comment]
If you don't have Slurm installed on your cluster, you should run Grappa jobs like any other MPI job, instead of using grappa_srun. The details depend on which version of MPI you use and whether your cluster has a different scheduler (PBS, GridEngine, etc.). Running hello_world.exe will probably involve a command like ```mpiexec -np 2 -hosts <comma-separated list of hosts> ./applications/demos/hello_world.exe```, but you'll have to check your MPI documentation to be sure.

**Comment by Qilewuqiong** [comment]
Thank you for replay.

**Comment by guowentian** [comment]
Hi, I am new to distributed computing. We want to test the performance of Grappa. Notice that the tests can be run by mpirun and the scripts provided(grappa_srun, i.e. on top of Slurm). Is there any difference between these running modes, specifically for performance ?

**Comment by nelsonje** [comment]
Performance should be identical.
