### ISSUE TITLE
problem to  execute a delegate call in  send_heap_message 

### ISSUE THREAD

**Issue by buaasun** [uwsampa/grappa#277]
Hello, I got error when execute a delegate call in  send_heap_message 
```c++
send_heap_message(core, [](){
    auto count=delegate::call(global_counter, [](Counter * counter){
    return counter->count();
   });
});
```
And I got error like this
```log
check failed: in_no_switch_region_  == false (1 vs. 0) Trying to context switch in no-switch region
```
 I am wondering if it is possible to execute a delegate call in  send_heap_message.

**Comment by bmyerz** [comment]
This is an assertion failure. It is there for safety.

You cannot perform a `delegate::call` inside of a `delegate::call` or a `send_heap_message`. You can, however, do a `send_heap_message` inside either one.

Aside: what is the overall operation you are intending to do?

**Comment by buaasun** [comment]
Thank you.
I need to send a message from  core A to core B. The message's struct and length are both changeable, so `delegate::call` is not enough and I have to use `send_heap_message` with a `payload`. I also have a global vector to save data version of each core (every message has a version), so I have to update the global version after core B received the message. what's the best way    to do this?
By the way, I found it is a slow roundtrip that  `send_heap_message`  to and then wait `send_heap_message`  back. Do you have any suggestion on communication in grappa, especially the operation of get remote  data. @bmyerz

**Comment by bmyerz** [comment]
@buaasun `send_heap_message` and `delegate::call` have high latency because Grappa assumes you want to aggregate the messages (it waits to send messages until more are queued up or a timeout is reached). If you need low latency could try using MPI send/receives directly (<- @nelsonje suggestions?)

**Comment by nelsonje** [comment]
We're working on a different approach to aggregation that will generally work better (lower latency when buffer full; better cache behavior) when sending payload messages. You can try out a primitive version of it by building the nelsonje/MPIRDMA branch instead of master (should be stable enough to use).

The other thing I'd say is that we generally avoid blocking delegates unless there's no other way to do it. When we need data from three machines A,B,C to do a computation, we'll send a message from A to B carrying data for C, collect the data from B, and send another message from B with both A and B's data to C. That might give you better performance overall.
