### ISSUE TITLE
Grappa 500 performance number

### ISSUE THREAD

**Issue by danghvu** [uwsampa/grappa#280]
Hello, I am looking at this paper:
http://sampa.cs.washington.edu/papers/grappa-tr-2014-02.pdf

What is the scaling number for BFS app on Graph500 ? I can't find it in the paper. Is there any improvement since then ?

**Comment by nelsonje** [comment]
Those numbers are ancient; Grappa has changed significantly since then. We haven't run any Graph500-specific numbers for a long time, although some of the BFS in our more recent paper use Kronecker graphs: http://sampa.cs.washington.edu/papers/grappa-usenix-2015.pdf (but probably all those numbers are relative).

You'd need to run on a modern Grappa to get modern numbers. I wouldn't expect us to be terribly competitive with other Graph500 entries; we haven't optimized for the Graph500 use case.

**Comment by danghvu** [comment]
I want to ask about the parameter to see how relatively it does with others (even at ancient time). Do you have the "scale" parameter for graph500 that you have run those benchmarks ?

**Comment by nelsonje** [comment]
You're talking about Figure 9a in the tech report? That's a scale 27 graph.

**Comment by nelsonje** [comment]
But please note: as we say in that paper, that BFS implementation has *none* of the common optimizations (like Beamer's direction-optimizing traversal) which can make a *huge* difference in performance. Comparing those numbers with published Graph500 results (which probably do include such optimizations) is really not a good idea.

**Comment by danghvu** [comment]
Thanks! I probably think of it relatively to bfs_simple reference implementation, which in Stampede has 2x performance of what you have. But I look forward to trying it in a more recent version.
